lanoseo_homepage:
    path:     /
    defaults: { _controller: lanoseoBundle:Default:index }

contact:
    path: /kontakt
    defaults: { _controller: lanoseoBundle:Default:contact }

login:
    path: /login
    defaults: { _controller: lanoseoBundle:Default:login }

register:
    path: /register
    defaults: { _controller: lanoseoBundle:Default:register }

carlist:
    path: /lista
    defaults: { _controller: lanoseoBundle:Default:carlist }

error:
    path: /error
    defaults: { _controller: lanoseoBundle:Default:error }

place_order:
    path: /place_order/{carId}
    defaults: { _controller: lanoseoBundle:Default:placeOrder }

reject_payment:
    path: /reject_payment/{orderId}
    defaults: { _controller: lanoseoBundle:Default:rejectPayment }

success_payment:
    path: /success_payment/{orderId}
    defaults: { _controller: lanoseoBundle:Default:successPayment }

summary:
    path: /summary/{carId}
    defaults: { _controller: lanoseoBundle:Default:summary }
payment:
    path: /payment/{orderId}
    defaults: { _controller: lanoseoBundle:Default:payment }
confirm_payment:
    path: /confirm_payment
    defaults: { _controller: lanoseoBundle:Default:confirmPayment }
logout:
    path: /logout
    defaults: { _controller: lanoseoBundle:Default:logout }